/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-01-22

 The MIT License (MIT)
 Copyright (c) 2019 STMicroelectronics

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 ******************************************************************************
 */

#include "stm32f4xx.h"
#include "stm32f4_discovery.h"
#include "vt100.h"
#include "serial.h"


int main(void)
{
	int i = 0;
	int k = 0;
	uint8_t sens = 1;
	char vie = '3';
	uint8_t inp_clav;
	uint8_t xv = 40;
	uint8_t yv = 20;
	uint8_t xa = 0;
	uint8_t ya = 3;
	uint8_t xm = 40;
	uint8_t ym = 21;
	char ship = 'o';
	char missile = '^';
	char alien = '#';

	serial_init(115200);
	vt100_clear_screen();

	/* Menu*/
	vt100_move(37, 2);
	serial_puts("SPACE INVADERS");
	vt100_move(34, 4);
	serial_puts("by Alexandre OLIVIER");
	vt100_move(20, 10);
	serial_puts("Q = Gauche / Espace = Missile / D = Droite");
	vt100_move(33, 20);
	serial_puts("Press <SPACE> to start");

	while (inp_clav != 32) /*32 ASCII de l'espace*/
	{
		inp_clav = serial_get_last_char();
	}
	vt100_clear_screen();
	while (1)
	{
		i++;
		k++;
		vt100_move(37, 2);
		serial_puts("SPACE INVADERS");
		vt100_move(1, 2);
		serial_puts("SCORE: ");
		vt100_move(65, 2);
		serial_puts("VIES: ");
		vt100_move(75, 2);
		serial_putchar(vie);
		vt100_move(xv, 20);
		serial_putchar(ship);
		inp_clav = serial_get_last_char();

		if (k == 20 || inp_clav == 32)
		{
			vt100_move(xm, ym);
			serial_putchar(' ');
			ym -= 1;
			vt100_move(xm, ym);
			serial_putchar(missile);

			if (ym == 3)
			{
				vt100_move(xm, 3);
				serial_putchar(' ');
				xm = xv;
				ym = 21;
			}
			k = 0;
		}


		if (inp_clav == 'd')
		{
			vt100_move(xv, 20);
			serial_putchar(' ');
			if (xv != 80)
			{
				xv += 1;
			}
			vt100_move(xv, 20);
			serial_putchar(ship);

		}
		if (inp_clav == 'q')
		{
			vt100_move(xv, 20);
			serial_putchar(' ');
			if (xv != 0)
			{
				xv -= 1;
			}
			vt100_move(xv, 20);
			serial_putchar(ship);
		}
		/*-----------------------------------------------------
			if (inp_clav == 'm')
		{
			while (ym != 3)
			{

				if (k > 1000000)
				{
					vt100_move(xv, ym);
					serial_putchar(' ');
					ym -= 1;
					vt100_move(xv, ym);
					serial_putchar(missile);
					k = 0;
				}
			}
			if (ym == 3)
			{
				vt100_move(xm, 3);
				serial_putchar(' ');
			}
		}
		 ---------alien------------------------------*/
		if (i == 15)
		{
			if (sens == 1)
			{
				vt100_move(xa, ya);
				serial_putchar(' ');
				xa += 1;
				vt100_move(xa, ya);
				serial_putchar(alien);
				if (xa == 80)
				{
					vt100_move(xa, ya);
					serial_putchar(' ');
					ya += 1;
					sens = 0;
				}

			}
			if (sens == 0)
			{
				vt100_move(xa, ya);
				serial_putchar(' ');
				xa -= 1;
				vt100_move(xa, ya);
				serial_putchar(alien);
				if (xa == 0)
				{
					vt100_move(xa, ya);
					serial_putchar(' ');
					ya += 1;
					sens = 1;
				}

			}
			if (ya == 20)
			{
				vt100_move(40, 20);
				serial_puts("LOSE");
			}
			i = 0;
		}

	}
}

/*
 * Callback used by stm32f4_discovery_audio_codec.c.
 * Refer to stm32f4_discovery_audio_codec.h for more info.
 */
void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size)
{
	/* TODO, implement your code here */
	return;
}

/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
uint16_t EVAL_AUDIO_GetSampleCallBack(void)
{
	/* TODO, implement your code here */
	return -1;
}
